#!/bin/bash
set -eu -o pipefail
trap 'echo "ERROR: line no = $LINENO, exit status = $?" >&2; exit 1' ERR

readonly DIR_SCRIPT="$(cd $(dirname ${0}); pwd)"
readonly DIR_LIB="${DIR_SCRIPT}/lib"

. "${DIR_LIB}/common.sh"

while read task
do
    
    [ -d "${task}" ] && \
        ( echo "delete Analysis => ${task}"; \
        mv "${task}"{,bak} )
done <"${FILE_ALL_TASK}"
